export const ADD_TO_BAG = 'ADD_TO_BAG';

export const REMOVE_FROM_BAG = 'REMOVE_FROM_BAG';

export const QUANTITY_INCREASED = 'QUANTITY_INCREASED';

export const QUANTITY_DECREASED = 'QUANTITY_DECREASED'